##
## EPITECH PROJECT, 2021
## B-CPE-110-LIL-1-1-bspushswap-quentin.desmettre
## File description:
## Makefile
##

SRC = ops.c

OBJ = $(SRC:.c=.o)

all:
	gcc -Wall -Wextra -c $(SRC) -I ../../include/
	mv $(OBJ) ../../
